# Generated by Django 5.2.6 on 2025-10-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_time',
        ),
    ]
